; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.32"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][version] = "1.1"

projects[backup_migrate][version] = "2.8"

projects[backup_migrate_files][version] = "1.x-dev"

projects[ctools][version] = "1.4"

projects[bulk_media_upload][version] = "1.x-dev"

projects[captcha][version] = "1.1"

projects[checklistapi][version] = "1.2"

projects[ckeditor][version] = "1.16"

projects[content_access][version] = "1.2-beta2"

projects[context][version] = "3.3"

projects[custom_breadcrumbs][version] = "2.0-beta1"

projects[devel][version] = "1.5"

projects[donate][version] = "1.0-beta1"

projects[donations_thermometer][version] = "1.0-alpha1"

projects[email][version] = "1.3"

projects[entity][version] = "1.5"

projects[media][version] = "1.4"

projects[google_analytics][version] = "2.0"

projects[html5_media][version] = "1.1"

projects[panels][version] = "3.4"

projects[imce][version] = "1.9"

projects[jcarousel][version] = "2.6"

projects[jquery_update][version] = "2.4"

projects[jqueryui_theme][version] = "1.0-alpha3"

projects[link][version] = "1.3"

projects[markdown][version] = "1.2"

projects[metatag][version] = "1.4"

projects[migrate][version] = "2.5"

projects[pay][version] = "1.0-alpha1"

projects[paypal_donate][version] = "1.6"

projects[piwik][version] = "2.6"

projects[plupload][version] = "1.6"

projects[randomblocks][version] = "1.1"

projects[robotstxt][version] = "1.2"

projects[seo_checklist][version] = "4.1"

projects[site_map][version] = "1.2"

projects[site_verify][version] = "1.1"

projects[token][version] = "1.5"

projects[views][version] = "3.8"

projects[views_accordion][version] = "1.0"

projects[webform][version] = "3.21"

projects[webform_classes][version] = "2.2"

projects[xmlsitemap][version] = "2.0"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[home][download][type] = ""
projects[home][download][url] = ""
projects[home][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[chelsea-cerulean][download][type] = ""
;projects[chelsea-cerulean][download][url] = ""
;projects[chelsea-cerulean][type] = "theme"
